import Head from 'next/head'

// getStaticProps- which allows us to fetch data at build time.
// getServerSideProps- which fetch data at every requests.

export default function Home({ articles }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {articles.map(article => <h3 key={article.id}>{article.title}</h3>)}
    </div>
  )
}

export const getStaticProps = async() => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }
}
